### ISSUE TITLE
Permissions for editing the wiki 

### ISSUE THREAD

**Issue by juandpenan** [CoreSenseEU/CoreSense4Home#2]
Hi, we were wondering if you could uncheck the option of "**Restrict editing to collaborators only**" and make the wiki public or maybe give Gentlebots team write permissions. As far as I know It is not possible to make pull requests by editing the wiki in the forked repos

Thanks in advance :smile:

**Comment by fmrico** [comment]
It should be fixed now

**Comment by juandpenan** [comment]
> It should be fixed now

it is working, thanks!
